<?php
namespace Packt\Table\Model\Movie;

use Packt\Table\Model\ResourceModel\Movie\CollectionFactory;;

class DataProvider extends \Magento\Ui\DataProvider\AbstractDataProvider
{
    /**
     * @var array
     */
    protected $_loadedData;

    public function __construct(
        $name,
        $primaryFieldName,
        $requestFieldName,
        CollectionFactory $employeeCollectionFactory,
        array $meta = [],
        array $data = []
    ) {
        $this->collection = $employeeCollectionFactory->create();
        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data);
    }

    public function getData()
    {
        if (isset($this->_loadedData)) {
            return $this->_loadedData;
        }
        $items = $this->collection->getItems();
        foreach ($items as $movie) {
            $this->_loadedData[$movie->getId()] = $movie->getData();
        }
        return $this->_loadedData;
    }
    public function addFilter(\Magento\Framework\Api\Filter $filter)
    {
        parent::addFilter($filter); // TODO: Change the autogenerated stub
    }
}